--SELECT ASCII('A') AS ASCIICODE from dual
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION GENERATEPEG(NAMA VARCHAR2, KODE VARCHAR2)
RETURN VARCHAR2
IS
	TEMP VARCHAR2(1);
	URUTAN VARCHAR(4);
	ASCI VARCHAR2(2);
BEGIN
	TEMP := SUBSTR(UPPER(NAMA), 1,1);
	SELECT ASCII(TEMP) AS ASCIICODE INTO ASCI FROM DUAL;
	ASCI := TO_NUMBER(ASCI)-64;
	SELECT MAX(SUBSTR(KODE_PEG,7,4)) INTO URUTAN FROM PEGAWAI;
	IF URUTAN IS NULL THEN
		RETURN '16' || LPAD(ASCI, 2, '0') || KODE || '0001';
	ELSE
		RETURN '16' || LPAD(ASCI, 2, '0') || KODE || LPAD(TO_NUMBER(URUTAN)+1, 4, '0');
	END IF;
END;
/


BEGIN
	DBMS_OUTPUT.PUT_LINE(GENERATEPEG('EDRIC', 11));
END;
/


CREATE OR REPLACE FUNCTION GENERATECUST(NAMA VARCHAR2)
RETURN VARCHAR2
IS
	TEMP VARCHAR2(1);
	URUTAN VARCHAR(3);
	ASCI VARCHAR2(2);
BEGIN
	TEMP := SUBSTR(UPPER(NAMA), 1,1);
	SELECT ASCII(TEMP) AS ASCIICODE INTO ASCI FROM DUAL;
	ASCI := TO_NUMBER(ASCI)-64;
	SELECT MAX(SUBSTR(5,6)) INTO URUTAN FROM CUSTOMER WHERE SUBSTR(KODE_CUST,1,4) = '03' || LPAD(ASCI, 2, '0');
	IF URUTAN IS NULL THEN 
		RETURN '03' || LPAD(ASCI, 2, '0') || '000001';
	ELSE
		RETURN '03' || LPAD(ASCI, 2, '0') || LPAD(TO_NUMBER(URUTAN)+1, 6, '0');
	END IF;
END;
/

BEGIN
	DBMS_OUTPUT.PUT_LINE(GENERATECUST('EDRIC'));
END;
/

CREATE OR REPLACE FUNCTION GENERATEGAJI(URUTAN VARCHAR2)
RETURN VARCHAR2
IS
	BT VARCHAR2(4);
BEGIN
	SELECT TO_CHAR(TO_DATE(SYSDATE, 'DD-MM-YYYY'), 'MMYY') INTO BT FROM DUAL;
	RETURN '07' || URUTAN || BT;
END;
/

