DROP TABLE PEGAWAI CASCADE CONSTRAINTS PURGE;
DROP TABLE PENGGAJIAN CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS PURGE;
DROP TABLE KAMAR CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTORAN_MENU CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTORAN_HJUAL CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTORAN_DJUAL CASCADE CONSTRAINT PURGE;
DROP TABLE HOTEL_HJUAL CASCADE CONSTRAINT PURGE;
DROP TABLE HOTEL_DJUAL CASCADE CONSTRAINT PURGE;
DROP TABLE PEGAWAI_DIVISI CASCADE CONSTRAINT PURGE;
DROP TABLE LAUNDRY_JENIS CASCADE CONSTRAINT PURGE;
DROP TABLE LAUNDRY_HJUAL CASCADE CONSTRAINT PURGE;
DROP TABLE LAUNDRY_DJUAL CASCADE CONSTRAINT PURGE;

CREATE TABLE PEGAWAI_DIVISI
(
	KODE_DIVISI VARCHAR2(5),
	NAMA_DIVISI VARCHAR2(20),
	GAJI_DIVISI NUMBER(8),
	CONSTRAINT PK_KODE_DIVISI PRIMARY KEY(KODE_DIVISI)
);

CREATE TABLE PEGAWAI
(
	KODE_PEG VARCHAR2(10),
	KODE_DIVISI VARCHAR2(10),
	NAMA_PEG VARCHAR2(50),
	ALAMAT_PEG VARCHAR2(50),
	TELP_PEG VARCHAR2(15),
	CONSTRAINT PK_KODE_PEG PRIMARY KEY(KODE_PEG),
	CONSTRAINT FK_KODE_DIVISI FOREIGN KEY(KODE_DIVISI)
	REFERENCES PEGAWAI_DIVISI(KODE_DIVISI)
);

CREATE TABLE PENGGAJIAN
(
	KODE_GAJI VARCHAR2(10),
	TGL_GAJI DATE,
	JUM_GAJI VARCHAR2(10),
	CONSTRAINT PK_KODE_GAJI PRIMARY KEY(KODE_GAJI)
);

CREATE TABLE CUSTOMER
(
	KODE_CUST VARCHAR2(10),
	NAMA_CUST VARCHAR2(50),
	ALAMAT_CUST VARCHAR2(50),
	TELP_CUST VARCHAR2(12),
	CONSTRAINT PK_KODE_CUST PRIMARY KEY(KODE_CUST)
);

CREATE TABLE KAMAR
(
	KODE_KAMAR VARCHAR2(10),
	NAMA_KAMAR VARCHAR2(20),
	HARGA_KAMAR NUMBER(8),
	CONSTRAINT PK_KODE_KAMAR PRIMARY KEY(KODE_KAMAR)
);

CREATE TABLE RESTORAN_MENU
(
	KODE_MAKANAN VARCHAR2(10),
	JENIS_MAKANAN VARCHAR2(10), /* MAKANAN ATAU MINUMAN*/
	NAMA_MAKANAN VARCHAR2(20),
	HARGA_MAKANAN NUMBER(8),
	CONSTRAINT PK_KODE_MAKANAN PRIMARY KEY(KODE_MAKANAN)
);

CREATE TABLE RESTORAN_HJUAL
(
	NOTA_RESTO VARCHAR2(10),
	KODE_CUST VARCHAR2(10),
	TGL_RESTO DATE,
	CONSTRAINT PK_NOTA_RESTO PRIMARY KEY(NOTA_RESTO),
	CONSTRAINT FK_KODE_CUST_RESTO FOREIGN KEY(KODE_CUST)
	REFERENCES CUSTOMER(KODE_CUST)
);

CREATE TABLE RESTORAN_DJUAL
(
	NOTA_RESTO VARCHAR2(10),
	KODE_MAKANAN VARCHAR2(10),
	CONSTRAINT FK_NOTA_RESTO FOREIGN KEY(NOTA_RESTO)
	REFERENCES RESTORAN_HJUAL(NOTA_RESTO),
	CONSTRAINT FK_KODE_MAKANAN FOREIGN KEY(KODE_MAKANAN)
	REFERENCES RESTORAN_MENU(KODE_MAKANAN)
);

CREATE TABLE HOTEL_HJUAL
(
	NOTA_HOTEL VARCHAR2(10),
	KODE_CUST VARCHAR2(10),
	TGL_IN DATE,
	CONSTRAINT PK_NOTA_HOTEL PRIMARY KEY(NOTA_HOTEL),
	CONSTRAINT FK_KODE_CUST_HOTEL FOREIGN KEY(KODE_CUST)
	REFERENCES CUSTOMER(KODE_CUST)
);

CREATE TABLE HOTEL_DJUAL
(
	NOTA_HOTEL VARCHAR2(10),
	KODE_KAMAR VARCHAR2(10),
	TGL_OUT DATE,
	CONSTRAINT FK_NOTA_HOTEL FOREIGN KEY(NOTA_HOTEL)
	REFERENCES HOTEL_HJUAL(NOTA_HOTEL),
	CONSTRAINT FK_KODE_KAMAR FOREIGN KEY(KODE_KAMAR)
	REFERENCES KAMAR(KODE_KAMAR)
);

CREATE TABLE LAUNDRY_JENIS
(
	KODE_LAUNDRY VARCHAR2(10),
	JENIS_LAUNDRY VARCHAR2(20), /*Contoh : cuci kering,basah,dll*/
	HARGA_LAUNDRY NUMBER(8),
	CONSTRAINT PK_KODE_LAUNDRY PRIMARY KEY(KODE_LAUNDRY)
);

CREATE TABLE LAUNDRY_HJUAL
(
	NOTA_LAUNDRY VARCHAR2(10),
	TGL_LAUNDRY DATE,
	CONSTRAINT PK_NOTA_LAUNDRY PRIMARY KEY(NOTA_LAUNDRY)
);

CREATE TABLE LAUNDRY_DJUAL
(
	NOTA_LAUNDRY VARCHAR2(10),
	KODE_LAUNDRY VARCHAR2(10),
	BERAT_LAUNDRY NUMBER(3), /*laundry hitung kiloan*/
	CONSTRAINT FK_NOTA_LAUNDRY FOREIGN KEY(NOTA_LAUNDRY)
	REFERENCES LAUNDRY_HJUAL(NOTA_LAUNDRY),
	CONSTRAINT FK_KODE_LAUNDRY FOREIGN KEY(KODE_LAUNDRY)
	REFERENCES LAUNDRY_JENIS(KODE_LAUNDRY)
);

INSERT INTO PEGAWAI VALUES ();